### ISSUE TITLE
Add codecov feature

### ISSUE THREAD

**Issue by theodumont** [18tbr/sunrise-refonte#1]
The codecov feature isn't currently working. It could be nice to make it work and add the corresponding badge in the README.md when it's done!

**Comment by 18tbr** [comment]
Indeed, thank you @theodumont for working hard on the project in spite of all the other classes you are taking at the moment. I will be looking forward to the addition of codecov on this repos ;-)

**Comment by 18tbr** [comment]
It doesn't seem like this will be implemented any time soon, because we don't actually need it given the priorities of the project.
